/**
 * Creates a fully self-contained staging directory for electron-builder by:
 *   1. Running `pnpm deploy --legacy --prod` → all production node_modules as
 *      real files (no pnpm store symlinks).
 *   2. Copying every desktop source file + the pre-generated NSIS resources
 *      into the staging dir so electron-builder can run with --projectDir.
 *   3. Moving the compiled installer output back to apps/desktop/dist/.
 *
 * The prebuild order must be:
 *   ensure-dist-writable → sync-installer-* → apply-nsis-* → materialize-deps
 * so that nsis/ is fully populated before we copy it into staging.
 */
import { execFileSync } from "node:child_process";
import { cpSync, rmSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const desktopDir = join(__dirname, "..");
const workspaceRoot = join(desktopDir, "..", "..");
const stagingDir = join(desktopDir, "_staging_probe");

// ── 1. Clean & deploy all prod deps into staging ───────────────────────────
console.log(`[materialize-deps] creating ephemeral staging workspace at ${stagingDir}`);
console.log("[materialize-deps] running pnpm deploy...");
if (existsSync(stagingDir)) {
  rmSync(stagingDir, { recursive: true, force: true });
}

execFileSync(
  "pnpm",
  ["deploy", "--filter=desktop", "--prod", "--legacy", stagingDir],
  {
    cwd: workspaceRoot,
    stdio: "inherit",
    shell: true,
    env: { ...process.env, CI: "true" },
  }
);

// ── 2. Copy desktop source files into staging ──────────────────────────────
const SOURCE_FILES = [
  "main.js",
  "preload.js",
  "asset-ipc-utils.js",
  "export-ipc-utils.js",
  "flat-config-ipc-utils.js",
  "constants.js",
  "splash.html",
  "splash-logo.png",
  "package.json",
];

console.log("[materialize-deps] copying source files...");
for (const file of SOURCE_FILES) {
  const src = join(desktopDir, file);
  if (existsSync(src)) cpSync(src, join(stagingDir, file), { force: true });
}

// ── 3. Copy NSIS build resources (pre-generated by sync-installer-* scripts) 
console.log("[materialize-deps] copying nsis build resources...");
cpSync(join(desktopDir, "nsis"), join(stagingDir, "nsis"), {
  recursive: true,
  force: true,
});

// ── 4. Patch staging package.json: fix extraResources absolute path ─────────
// When electron-builder runs from _staging, relative paths like
// "../dashboard/.next/standalone" resolve to apps/desktop/dashboard (wrong).
// We rewrite the staging package.json to use the real absolute path.
console.log("[materialize-deps] patching staging package.json paths...");
const stagingPkgPath = join(stagingDir, "package.json");
const stagingPkg = JSON.parse(readFileSync(stagingPkgPath, "utf8"));
const standaloneAbsPath = join(workspaceRoot, "apps", "dashboard", ".next", "standalone").replace(/\\/g, "/");
if (stagingPkg.build?.extraResources) {
  for (const res of stagingPkg.build.extraResources) {
    if (res.from && res.from.includes("dashboard")) {
      res.from = standaloneAbsPath;
    }
  }
}
writeFileSync(stagingPkgPath, JSON.stringify(stagingPkg, null, 2));

// ── 5. Run electron-builder from staging, output → apps/desktop/dist ───────
console.log("[materialize-deps] running electron-builder from staging...");
const distDir = join(desktopDir, "dist");
execFileSync(
  "npx",
  [
    "electron-builder",
    "--projectDir", stagingDir,
    `--config.directories.output=${distDir}`,
    "--config.directories.buildResources=nsis",
  ],
  { cwd: desktopDir, stdio: "inherit", shell: true }
);

// ── 5. Cleanup staging ─────────────────────────────────────────────────────
rmSync(stagingDir, { recursive: true, force: true });
console.log("[materialize-deps] done — installer written to apps/desktop/dist/");
