export {
  BRIDGE_MESSAGE_TYPE,
  type BridgeMessage,
  type ConfigUpdateMode,
  type DiagnosticsPayloadMessage,
  type IframeReadyMessage,
  type LoadTemplateMessage,
  type RequestDiagnosticsMessage,
  type UpdateConfigMessage,
  isBrandingPatch,
  isDiagnosticsPayloadMessage,
  isGameMasterConfig,
  isIframeReadyMessage,
  isLoadTemplateMessage,
  isRequestDiagnosticsMessage,
  isUpdateConfigMessage,
} from "./bridge";

export {
  buildConfigFromSchema,
  buildConfigWithFrozenSystem,
  exportClientPayload,
  getConfigValue,
  mergeBrandingPatch,
  migrateLegacyConfig,
  normalizeGameMasterConfig,
} from "./config-utils";

export {
  assertPermission,
  canAccess,
  filterSchemaByMode,
  filterSchemaControls,
  PermissionDeniedError,
  surfaceForMode,
  type RegistryResource,
} from "./permissions";

export {
  bumpSemverPatch,
  gameSchemaFromManifest,
  gameSchemaFromManifestForMode,
  isTemplateManifest,
  type JsonSchemaControlExtension,
  type TemplateCatalogEntry,
  type TemplateConfigJsonSchema,
  type TemplateManifest,
  type TemplateManifestStatus,
} from "./template-manifest";

export {
  DEFAULT_BRANDING_SETTINGS,
  DEFAULT_GAME_MASTER_CONFIG,
  DEFAULT_GAME_TEMPLATE_ID,
  DEFAULT_SCHEMA_VERSION,
  DEFAULT_SYSTEM_SETTINGS,
  GAME_TEMPLATE_IDS,
  getDomOverlayForUi,
  getPrimaryBrandColor,
  isGameTemplateId,
  isLegacyGameMasterConfig,
  parseGameTemplateId,
  type AnimationClipMapping,
  type AnimationDefinition,
  type AppMode,
  type BrandingPatch,
  type BrandingSettings,
  type BuiltinGameTemplateId,
  type ConfigRootCategory,
  type ControlFieldSchema,
  type ControlSchema,
  type ControlSurface,
  type ControlType,
  type ControlValue,
  type DeepPartial,
  type DOMOverlayConfig,
  type GameMasterConfig,
  type GameMasterConfigMeta,
  type GameplayConfig,
  type GameSchema,
  type GameTemplateId,
  type LegacyGameMasterConfig,
  type PublishedTemplateBundle,
  type RewardRuleConfig,
  type SpriteSheetDefinition,
  type SystemSettings,
  type ThemeConfig,
  type WinConditionConfig,
} from "./types";
