#!/usr/bin/env node
/**
 * Scans the unified templates/ directory for manifest.json files and generates
 * a static registry for Next.js (no import.meta.glob).
 *
 * All templates live in a flat structure: templates/{templateId}/
 * Status (draft | published) in manifest.json determines visibility —
 * no folder-based library/development split.
 */
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const templatesRoot = path.resolve(scriptDir, "../src/templates");
const outputPath = path.join(templatesRoot, "manifest-registry.generated.ts");
const publishedOutputPath = path.join(
  templatesRoot,
  "published-system-registry.generated.ts",
);

/** Directories that are not template folders and should be skipped. */
const SKIP_DIRS = new Set(["library", "development"]);

function listTemplateIds(): string[] {
  if (!existsSync(templatesRoot)) return [];

  return readdirSync(templatesRoot, { withFileTypes: true })
    .filter(
      (entry) =>
        entry.isDirectory() &&
        !SKIP_DIRS.has(entry.name) &&
        existsSync(path.join(templatesRoot, entry.name, "manifest.json")),
    )
    .map((entry) => entry.name)
    .sort();
}

function buildPublishedSystemSection(templateIds: string[]): {
  imports: string[];
  entries: string[];
} {
  const imports: string[] = [];
  const entries: string[] = [];

  templateIds.forEach((id, index) => {
    const filePath = path.join(templatesRoot, id, "published-system.json");
    if (!existsSync(filePath)) return;
    const binding = `published${index}`;
    imports.push(`import ${binding} from "./${id}/published-system.json";`);
    entries.push(`  "${id}": ${binding} as SystemSettings,`);
  });

  return { imports, entries };
}

function main(): void {
  const templateIds = listTemplateIds();
  const published = buildPublishedSystemSection(templateIds);

  const manifestImports = templateIds
    .map((id, index) => `import template${index} from "./${id}/manifest.json";`)
    .join("\n");

  const manifestEntries = templateIds
    .map((_id, index) => `template${index}`)
    .join(", ");

  const manifestContent = `/* eslint-disable */
// AUTO-GENERATED by apps/game-engine/scripts/sync-manifest-registry.ts — do not edit.
import type { TemplateManifest } from "@mashedgames/shared";

${manifestImports}

export const ALL_MANIFESTS = [${manifestEntries}] as TemplateManifest[];
`;

  const publishedContent = `/* eslint-disable */
// AUTO-GENERATED by apps/game-engine/scripts/sync-manifest-registry.ts — do not edit.
import type { GameTemplateId, SystemSettings } from "@mashedgames/shared";

${published.imports.join("\n")}

export const PUBLISHED_SYSTEM_BY_ID: Partial<Record<GameTemplateId, SystemSettings>> = {
${published.entries.join("\n")}
};
`;

  if (!existsSync(templatesRoot)) {
    mkdirSync(templatesRoot, { recursive: true });
  }

  writeFileSync(outputPath, manifestContent, "utf8");
  writeFileSync(publishedOutputPath, publishedContent, "utf8");
  console.log(`Wrote manifest registry (${templateIds.length} templates: ${templateIds.join(", ")})`);
}

main();
