#!/usr/bin/env node
/**
 * Scans templates/library and templates/development for manifest.json files
 * and generates a static registry for Next.js (no import.meta.glob).
 */
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const templatesRoot = path.resolve(scriptDir, "../src/templates");
const outputPath = path.join(
  templatesRoot,
  "manifest-registry.generated.ts",
);

function listTemplateIds(folder: string): string[] {
  const dir = path.join(templatesRoot, folder);
  if (!existsSync(dir)) return [];

  return readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) =>
      existsSync(path.join(dir, name, "manifest.json")),
    )
    .sort();
}

function buildSection(
  folder: "library" | "development",
  ids: string[],
): { imports: string[]; varName: string; entries: string[] } {
  const varName =
    folder === "library" ? "LIBRARY_MANIFESTS" : "DEVELOPMENT_MANIFESTS";
  const imports: string[] = [];
  const entries: string[] = [];

  ids.forEach((id, index) => {
    const binding = `${folder}${index}`;
    imports.push(
      `import ${binding} from "./${folder}/${id}/manifest.json";`,
    );
    entries.push(binding);
  });

  return { imports, varName, entries };
}

function buildPublishedSystemSection(libraryIds: string[]): {
  imports: string[];
  entries: string[];
} {
  const imports: string[] = [];
  const entries: string[] = [];

  libraryIds.forEach((id, index) => {
    const filePath = path.join(templatesRoot, "library", id, "published-system.json");
    if (!existsSync(filePath)) return;
    const binding = `published${index}`;
    imports.push(
      `import ${binding} from "./library/${id}/published-system.json";`,
    );
    entries.push(`  "${id}": ${binding} as SystemSettings,`);
  });

  return { imports, entries };
}

function main(): void {
  const libraryIds = listTemplateIds("library");
  const developmentIds = listTemplateIds("development");

  const library = buildSection("library", libraryIds);
  const development = buildSection("development", developmentIds);
  const published = buildPublishedSystemSection(libraryIds);

  const manifestContent = `/* eslint-disable */
// AUTO-GENERATED by apps/game-engine/scripts/sync-manifest-registry.ts — do not edit.
import type { TemplateManifest } from "@mashedgames/shared";

${[...library.imports, ...development.imports].join("\n")}

export const ${library.varName} = [${library.entries.join(", ")}] as TemplateManifest[];
export const ${development.varName} = [${development.entries.join(", ")}] as TemplateManifest[];
`;

  const publishedPath = path.join(
    templatesRoot,
    "published-system-registry.generated.ts",
  );
  const publishedContent = `/* eslint-disable */
// AUTO-GENERATED by apps/game-engine/scripts/sync-manifest-registry.ts — do not edit.
import type { GameTemplateId, SystemSettings } from "@mashedgames/shared";

${published.imports.join("\n")}

export const PUBLISHED_SYSTEM_BY_ID: Partial<Record<GameTemplateId, SystemSettings>> = {
${published.entries.join("\n")}
};
`;

  writeFileSync(outputPath, manifestContent, "utf8");
  writeFileSync(publishedPath, publishedContent, "utf8");
  console.log(
    `Wrote manifest registry (${libraryIds.length} library, ${developmentIds.length} development)`,
  );
}

main();
