/* eslint-disable */
// AUTO-GENERATED by apps/game-engine/scripts/sync-manifest-registry.ts — do not edit.
import type { TemplateManifest } from "@mashedgames/shared";

import template0 from "./catch-game-demo/manifest.json";
import template1 from "./sdaf/manifest.json";

export const ALL_MANIFESTS = [template0, template1] as TemplateManifest[];
