/* eslint-disable */
// AUTO-GENERATED by apps/game-engine/scripts/sync-manifest-registry.ts — do not edit.
import type { GameTemplateId, SystemSettings } from "@advergaming/shared";

import published0 from "./library/clicker/published-system.json";
import published1 from "./library/dice-poker/published-system.json";

export const PUBLISHED_SYSTEM_BY_ID: Partial<Record<GameTemplateId, SystemSettings>> = {
  "clicker": published0 as SystemSettings,
  "dice-poker": published1 as SystemSettings,
};
