/* eslint-disable */
// AUTO-GENERATED by apps/game-engine/scripts/sync-manifest-registry.ts — do not edit.
import type { GameTemplateId, SystemSettings } from "@mashedgames/shared";

import published0 from "./library/catch-game-demo/published-system.json";

export const PUBLISHED_SYSTEM_BY_ID: Partial<Record<GameTemplateId, SystemSettings>> = {
  "catch-game-demo": published0 as SystemSettings,
};
